# frozen_string_literal: true

class GameRules
  START_BANK = 0
  BET_SIZE = 10
  START_BALANCE = 100
  MAX_CARDS_COUNT = 3
  PASS_SCORE = 18
  TIME = 2
  DEFAULT_POOL_SIZE = 5
  WIN_SCORE = 21
  DEFAULT_VALUE = 10
  ACE_MIN_VALUE = 1
  ACE_MAX_VALUE = 11
end
